### ISSUE TITLE
"usínání systému"

### ISSUE THREAD

**Issue by roman-dvorak** [UniversalScientificTechnologies/SolarPatrolTelescope#1]
systém se údajně bez zapnutí hodinového stroje sám vypne/uspí. Spíše bych to viděl na nějakou chybu v kódu... Než že by systém "usínal". Stane se to pouze pokuď se systém spustí bez zapnutí hodinového stroje.

**Comment by kaklik** [comment]
@hanuson1 Nedávno implementoval ODROID watchdog do stanice Geozoru. 
https://github.com/CTU-FEE-LEEE/ISMS/blob/master/SW/watchdog.py

Možná by to tenhle problém řešilo taky.

**Comment by roman-dvorak** [comment]
Tato záležitost již prý není pozorována (a v tomto stavu se dalekohled nachází relativně často). Ale neznám vysvětlení toho problému.
